# frontend/Dockerfile
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Install a lightweight HTTP server for static files
RUN npm install -g serve

EXPOSE 3000
EXPOSE 10000

CMD ["serve", "-s", "dist", "-l", "3000"]