services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: render
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
    buildCommand: npm run build
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: VITE_API_BASE_URL
        value: https://api-gateway-71gx.onrender.com
    healthCheckPath: /

  - type: web
    name: api-gateway
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: render
    rootDir: backend/api-gateway
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths: 
        - backend/api-gateway/**
    # buildCommand: ""
    # startCommand: ""
    envVars:
      - key: PORT
        value: "8443"
      - key: API_BASE_URL
        value: https://api-gateway-71gx.onrender.com
      - key: HEALTH_PORT
        value: "10000"
      - key: USER_MANAGEMENT_URL
        value: https://user-management-lsdg.onrender.com
    healthCheckPath: /health

  - type: web
    name: user_management
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: render
    rootDir: backend/microservices/user_management
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/microservices/user_management/**
    envVars:
      - key: PORT
        value: "9001"
    healthCheckPath: /health

  - type: web
    name: game_service
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: render
    rootDir: backend/microservices/game_service
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/microservices/game_service/**
    envVars:
      - key: PORT
        value: "9002"
      - key: HEALTH_PORT
        value: "10000"
    healthCheckPath: /health
   
